<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qml" nsURI="http://www.example.org/qml" nsPrefix="qml">
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//Feature"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//Group" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualityrequirement" eType="#//QualityRequirement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//Group"
        eOpposite="#//Group/feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="2"
        upperBound="-1" eType="#//Feature" eOpposite="#//Feature/group"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupType" eType="#//GroupType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GroupType">
    <eLiterals name="ALT"/>
    <eLiterals name="OR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequireConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredFeature" upperBound="-1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredAttribute" upperBound="-1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredAttributeValue"
        upperBound="-1" eType="#//AttributeValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExcludeConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludedFeature" upperBound="-1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludedAttribute" upperBound="-1"
        eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludedAttributeValue"
        upperBound="-1" eType="#//AttributeValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenValueAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//BaseType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualityRequirement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualityproperty" lowerBound="1"
        upperBound="-1" eType="#//QualityProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualityProperty" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="measure" upperBound="-1"
        eType="#//Measure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" eType="#//QualityNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implentedBy" upperBound="-1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvedFeature" upperBound="-1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fairness" eSuperTypes="#//QualityProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//FairnessType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Explainability" eSuperTypes="#//QualityProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explainabilityLevel" eType="#//Level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Measure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="threshold" eType="#//Threshold"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementedBy" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Threshold">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Level">
    <eLiterals name="LOW"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="HIGH" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QualityNature">
    <eLiterals name="REQUIRED"/>
    <eLiterals name="OBSERVED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FairnessType">
    <eLiterals name="PREPROCESSING"/>
    <eLiterals name="INPROCESSING" value="1"/>
    <eLiterals name="POSTPROCESSING" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BaseType">
    <eLiterals name="INTEGER"/>
    <eLiterals name="FLOAT" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="STRING" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionValueAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributevalue" lowerBound="1"
        upperBound="-1" eType="#//AttributeValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType"/>
  </eClassifiers>
</ecore:EPackage>
